variable "project_display_name" {}
variable "notebook_session_display_name" {}
variable "notebook_session_notebook_session_configuration_details_shape" {}
variable "notebook_session_notebook_session_configuration_details_block_storage_size_in_gbs" {}
variable "ods_rt_display_name" {}
variable "ods_sl_display_name" {}
variable "ods_subnet_display_name" {}
variable "ods_subnet_dns_label" {}
variable "ods_subnet_cidr" {}
variable "compartment_id" {}
variable "vcn_id" {}
variable "vcn_default_dhcp_options_id" {}
variable "ng_id" {}
variable "sg_id" {}
variable "service_cidr_block" {}
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "ods_group_is_deployed" {}
variable "ods_group_name" {}
variable "ods_group_description" {}
variable "ods_dynamic_group_is_deployed" {}
variable "ods_dynamic_group_name" {}
variable "ods_dynamic_group_description" {}
variable "ods_policy_is_deployed" {}
variable "ods_policy_name" {}
variable "ods_policy_description" {}
variable "compartment_policy_statement_substring" {}