variable "bucket_name" {}
variable "bucket_access_type" {}
variable "bucket_storage_tier" {}
variable "bucket_versioning" {}
variable "objectstorage_namespace" {}
variable "compartment_id" {}
variable "bucket_group_is_deployed" {}
variable "bucket_group_name" {}
variable "bucket_group_description" {}
variable "bucket_policy_is_deployed" {}
variable "bucket_policy_name" {}
variable "bucket_policy_description" {}
variable "compartment_policy_statement_substring" {}
variable "tenancy_ocid" {}