variable "odi_workspace_display_name" {}
variable "workspace_is_private_network_enabled" {}
variable "odi_rt_display_name" {}
variable "odi_sl_display_name" {}
variable "odi_subnet_display_name" {}
variable "odi_subnet_dns_label" {}
variable "odi_subnet_cidr" {}
variable "compartment_id" {}
variable "vcn_id" {}
variable "vcn_default_dhcp_options_id" {}
variable "ng_id" {}
variable "sg_id" {}
variable "service_cidr_block" {}
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "odi_group_is_deployed" {}
variable "odi_group_name" {}
variable "odi_group_description" {}
variable "odi_dynamic_group_is_deployed" {}
variable "odi_dynamic_group_name" {}
variable "odi_dynamic_group_description" {}
variable "odi_policy_is_deployed" {}
variable "odi_policy_name" {}
variable "odi_policy_description" {}
variable "compartment_policy_statement_substring" {}