variable "vcn_display_name" {}
variable "vcn_dns_label" {}
variable "ng_display_name" {}
variable "sg_display_name" {}
variable "vcn_cidrs" {}
variable "compartment_id" {}
variable "service_id" {}
variable "vcn_group_is_deployed" {}
variable "vcn_group_name" {}
variable "vcn_group_description" {}
variable "vcn_policy_is_deployed" {}
variable "vcn_policy_name" {}
variable "vcn_policy_description" {}
variable "compartment_policy_statement_substring" {}
variable "tenancy_ocid" {}